FILENAME=599-C-14425910
CC=cilly
CFLAGS=--save-temps -fno-optimize-sibling-calls -fno-strict-aliasing -fno-asm
LDFLAGS=-lm -s -O2
all:
	$(CC) $(CFLAGS) -c $(FILENAME).c -o $(FILENAME).o
	$(CC) $(FILENAME).o -o $(FILENAME) $(LDFLAGS)
.PHONY: clean
clean:
	rm -f *.o $(FILENAME)
